fix: 카카오 로그인 500에러 해결
healthiin/server pull request #40
Opened 2022-09-24 11:32 UTC by puleugo

2022-09-24 11:52 UTC, adrinerDP requested changes
ㄴㄴ ㄱㄷㄱㄷ

2022-09-25 03:31 UTC, adrinerDP requested changes
이 리뷰는 시속 1**km로 달리는 중에 작성되었습니다

2022-09-25 03:31 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>        }
별도의 함수로 따로 뽑아서 처리하는 방법이 더 깔끔하지 않을까 합니다.

2022-09-25 03:31 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    );
AuthService에 벤더사의 메서드가 계속 추가된다면 확장성 있는 설계가 아니지 않을까 하는 우려가 있습니다.

2022-09-25 03:31 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +      return { id: createdUserId, isFreshman: true };
메서드 이름과 실제 하는 동작이 일치하지 않는 것 같습니다

2022-09-25 03:31 UTC, adrinerDP commented on src/app/auth/authentication/dtos/oauth-user-response.ts
> +  }
DTO 레벨에서 신규 가입 여부를 판단하는데 서비스 레이어에서 추가로 계산 해줄 필요는 없지 않나 싶습니다.

2022-09-25 03:31 UTC, adrinerDP commented on src/app/user/dtos/user-profile.response.ts
> +    this.isFreshman = user.createdAt === user.updatedAt;
여기는 getter를 사용하지 않고 property 방법으로 처리한 이유가 따로 있나요?

2022-09-25 03:31 UTC, adrinerDP commented on src/app/user/user.service.ts
> +    const { ...profile } = data;
deep copy를 수행하는 이유가 있나요?

2022-09-25 03:31 UTC, adrinerDP commented on src/app/user/user.service.ts
>      });
여기서도 deep copy를 추가로 수행하는데 비효율적일 가능성이 있어 보입니다.

2022-09-25 03:31 UTC, adrinerDP commented on src/migrations/1664035962513-create_users_table.ts
> +export class createUsersTable1664035962513 implements MigrationInterface {
마이그레이션 손대지 말아주세요.

2022-09-25 06:53 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
> +    );
추후에 개선하겠습니ㅏㄷ.

2022-09-26 02:18 UTC, adrinerDP approved these changes
배포 결과 보고 롤백 준비 해야 합니다

2022-09-26 02:18 UTC, merged