refactor: 카카오 로그인 리팩토링
healthiin/server pull request #43
Opened 2022-09-26 15:34 UTC by puleugo

2022-09-26 15:35 UTC, adrinerDP requested changes

2022-09-26 15:35 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>      );
네트워크 이슈에 대한 핸들링도 들어가 있어야 할 것 같습니다.

2022-09-26 15:38 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
> +        username: userData.id,
생각을 해보진 않았는데 `kakao:${userData.id}`이런 방식으로 구현할까합니다.

2022-09-26 15:40 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +        username: userData.id,
좋습니다 그렇게 반영 해주세요~

2022-09-26 15:45 UTC, puleugo commented on src/migrations/1663786622031-create_users_table.ts
> +  name = 'createUsersTable1663786622031';
이건 반영되지 않은 잘못된 마이그레이션을 롤백하는 부분입니다.
이전에 머지된 기록까지 가져와졌네요.

2022-09-26 15:48 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
>      );
네트워크 이슈 시 토큰값이 제대로 불러와지지 않아 data 변수에 undefined가 반환됩니다. 
이를 KakaoOAuthFailedException()를 통해 예외 처리를 해주었으므로 문제가 없어보입니다.

2022-09-26 15:48 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>      );
timeout도 핸들링 되나요?

2022-09-26 15:52 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
>      );
카카오: "부하가 순간 급증하여 지연될 때 가장 늦은 응답은 250ms 입니다."
https://devtalk.kakao.com/t/timeout/81365

카카오에서 어느정도 처리해주는데 timeout 핸들링을 따로 잡아줄 필요가 있나요?
OAuth를 처음 구현해봐서 보통 처리해주는지 모릅니다.

2022-09-26 16:02 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
>      );
Timeout 예외처리 했습니다 :D

2022-09-26 16:08 UTC, adrinerDP requested changes

2022-09-26 16:08 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    }
이렇게 된 상황에서 실제로 Network Timeout이 발생하면 55번 라인에서 exception throw가 이루어지고, 
아래에 있는 503 Gateway Timeout 판단 로직으로 넘어가지 않을 것 같습니다. 
Gateway Timeout은 상대방측 네트워크의 문제이기 때문에, 역시 이를 가지고 판단하는 것 또한 부적잘해 보입니다.

혹시 테스트 결과 있으면 아래에 첨부해주시면 좋겠습니다.

2022-09-26 16:08 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    userData.id = 'kakao:' + userData.id;
const object 내용을 직접 변경하는 것 보다는 실제로 사용하는 곳에서 prefix를 달아주는 것이 좋을 것 같습니다.

2022-09-26 16:08 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>      }
실제 유저 가입 처리는 외부의 호출자가 하는 편이 좋을 것 같습니다.
N개의 벤더사가 있는 경우, 사용자를 영속화하는 중복 코드가 N개가 생길 우려가 있습니다.

2022-09-26 16:08 UTC, adrinerDP commented on src/migrations/1663786622031-create_users_table.ts
> +  name = 'createUsersTable1663786622031';
git rebase를 통해 삭제하면 좋을 것 같습니다.

2022-09-26 16:13 UTC, adrinerDP commented
rebase 해뒀습니다

2022-09-26 16:21 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
> +    }
<img width="471" alt="image" src="https://user-images.githubusercontent.com/75980875/192328930-9aae86f0-d7b2-4e08-adaf-d4145aed88a4.png">
status의 return 타입이 `number`이기 때문에 throw가 던져지지 않습니다.

2022-09-26 16:22 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    }
timeout 상황 상정하고 코드 돌려보셨나요

2022-09-26 16:27 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
>      }
문제는 이해했습니다.
그럼 `각 회원을 관리하는 테이블`과 `특정 회원의 OAuth 정보 관리 테이블`을 1:N으로 관리하는 방식으로 구현하겠습니다.

2022-09-26 16:50 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    }
https://www.google.com/search?q=axios+mock+timeout

2022-09-26 16:50 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>      }
이건 코드 디자인에 대한 리뷰였는데, 그 부분도 문제가 될 수 있을 것 같습니다.

2022-09-26 16:54 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
>      }
이부분은 테이블 구성을 고민해봐야할 것 같아서 우선은 패스하고 구글 로그인 때 보완하겠습니다.
이번 PR에서는 지적해주신 스타일 부분만 수정하겠습니다.

2022-09-26 17:00 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
>      }
말씀해주신 스타일에 대해 이해가 가지 않는데 이 메소드는 카카오 로그인만을 처리하는 메소드이기 떄문에 다른 벤더사는 고려할 필요가 없지 않나요?

2022-09-26 17:02 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>      }
1. 카카오 로그인을 통해 프로필을 받는다
2. 받은 프로필을 가공한다
3. 가공한 프로필을 영속화한다

2022-09-27 11:23 UTC, puleugo commented on src/app/auth/authentication/authentication.service.ts
> +    }
해결했습니다.

2022-09-27 16:25 UTC, adrinerDP requested changes

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +
1. 의미 없는 코드인 것 같은데요, 여기서 수행하는 판단 로직을 객체 생성 시점으로 넘기면 되지 않을까요?
2. let 키워드를 사용해서 Object를 정의한 후에 내부 변경을 일으키는 방식은 클린하지 못한 것 같습니다.
3. async 하지 않은데 async 키워드를 사용하고, 이를 호출하는 곳에서 await 처리를 해주는 이유가 있을까요?

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    axios.defaults.timeout = 1000;
서비스에서 외부 서비스를 호출하게 되는 경우가 많이 생길 것 같은데,
API Client의 공통 설정을 깔끔하게 처리할 수 있었으면 좋겠습니다.

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +        }
타 서비스의 Gateway Timeout까지 핸들링 할 필요는 없을 것 같습니다.

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    const user = await this.userService.findByUsername('kakao:' + userData.id);
```suggestion
    const user = await this.userService.findByUsername(`kakao:${userData.id}`);
```

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
>      }
기존 유저의 경우 조회 후 업데이트를 수행하게 되어 2x의 I/O가 발생하게 되는데, 최적화 방안이 없을까요?

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +    };
타입은 따로 빼는 것이 맞을 것 같습니다.

2022-09-27 16:25 UTC, adrinerDP commented on src/app/auth/authentication/authentication.service.ts
> +  async transformKakaoDataToUser(data: any): Promise<UserKakaoResponse> {
no any

2022-09-27 16:25 UTC, adrinerDP commented on src/domain/errors/auth.errors.ts
> +}
에러 메시지가 단순히 '요청 실패' 만을 알려주기 위함이라면 좀 더 general 한 custom exception name을 지정해주는 것이 좋을 것 같습니다.

2022-09-28 12:58 UTC, puleugo commented on src/app/user/dtos/user-create.request.ts
> +  age_range!: string;
카카오에서 던져주는 오브젝트입니다.

2022-11-12 08:20 UTC, closed without merging